### <center>  ***Import Libraries*** </center>

In [65]:
# Import Libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns
import datetime as dt 

from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler,MinMaxScaler,RobustScaler
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.impute import SimpleImputer,KNNImputer
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

### Import dataset

In [66]:
titanic = pd.read_csv("C:\\Users\\coola\\OneDrive\\Desktop\\Machine Learning Case Study\\tested.csv")
titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [67]:
# Checking Dimension of data

In [68]:
print('Observation of Table',titanic.shape[0])
print('Variable of table',titanic.shape[1])

Observation of Table 418
Variable of table 12

In [69]:
# Check data info

In [70]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Survived     418 non-null    int64
 2   Pclass       418 non-null    int64
 3   Name         418 non-null    object
 4   Sex          418 non-null    object
 5   Age          332 non-null    float64
 6   SibSp        418 non-null    int64
 7   Parch        418 non-null    int64
 8   Ticket       418 non-null    object
 9   Fare         417 non-null    float64
 10  Cabin        91 non-null     object
 11  Embarked     418 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 39.3+ KB

In [71]:
# Check null values

titanic.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [72]:
# Checking Percentage of null 

titanic.isna().sum()/titanic.shape[0] * 100

PassengerId     0.000000
Survived        0.000000
Pclass          0.000000
Name            0.000000
Sex             0.000000
Age            20.574163
SibSp           0.000000
Parch           0.000000
Ticket          0.000000
Fare            0.239234
Cabin          78.229665
Embarked        0.000000
dtype: float64

In [73]:
# checking the dependent variable is balance or not

titanic.Survived.value_counts()

Survived
0    266
1    152
Name: count, dtype: int64

In [74]:
titanic.drop(columns=['PassengerId','Name'],inplace=True)

In [75]:
titanic['Ticket_Prefix'] = titanic['Ticket'].str.extract(r'([A-Za-z./]+)')

In [76]:
titanic.Ticket_Prefix.value_counts()

Ticket_Prefix
PC            32
C.A.          19
A/             8
SOTON/O.Q.     8
SC/PARIS       6
W./C.          5
S.O./P.P.      4
CA             4
F.C.C.         4
CA.            4
C              3
STON/O         3
S.O.C.         2
SC/AH          2
F.C.           2
A.             2
AQ/            2
SC/Paris       1
SC             1
SOTON/O        1
LP             1
PP             1
SC/A           1
SOTON/OQ       1
STON/OQ.       1
W.E.P.         1
A./            1
SC/A.          1
S.C./PARIS     1
Name: count, dtype: int64

In [77]:
titanic.drop(columns=['Ticket','Ticket_Prefix'],inplace=True)

In [78]:
titanic.Sex.value_counts()

Sex
male      266
female    152
Name: count, dtype: int64

In [79]:
titanic.Embarked.value_counts()

Embarked
S    270
C    102
Q     46
Name: count, dtype: int64

In [80]:
titanic.Cabin.value_counts()

Cabin
B57 B59 B63 B66    3
B45                2
C89                2
C55 C57            2
A34                2
                  ..
E52                1
D30                1
E31                1
C62 C64            1
C105               1
Name: count, Length: 76, dtype: int64

In [81]:
titanic['Deck'] = titanic['Cabin'].str[0]

In [82]:
titanic['Deck']=np.where(titanic.Deck.isna(),'Unknown',titanic.Deck)

In [83]:
titanic.drop(columns='Cabin',inplace=True)

In [84]:
titanic.select_dtypes('object').describe()

         Sex Embarked     Deck
count    418      418      418
unique     2        3        8
top     male        S  Unknown
freq     266      270      327

In [85]:
x = titanic.loc[::,titanic.columns.difference(['Survived'])]
y = titanic['Survived']

In [86]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=10)

In [87]:
x_train.shape

(292, 8)

In [88]:
x_test.shape

(126, 8)

In [89]:
y_train.shape

(292,)

In [90]:
y_test.shape

(126,)

In [91]:
# KNN impute only numerical column

In [92]:
#imputation=SimpleImputer(strategy='mean')
#X_train[['Age']]=imputation.fit_transform(X_train[["Age"]])
#X_test[['Age']]=imputation.fit_transform(X_test[["Age"]])

In [93]:
imputer=SimpleImputer(strategy='most_frequent')
x_train[['Embarked']]=imputer.fit_transform(x_train[["Embarked"]])
x_test[['Embarked']]=imputer.fit_transform(x_test[["Embarked"]])

In [94]:
num = x_train.select_dtypes(['int64','float']).columns
Knn_imputer=KNNImputer(n_neighbors=4,weights='uniform')
x_train[num]=Knn_imputer.fit_transform(x_train[num])
x_test[num]=Knn_imputer.transform(x_test[num])

In [95]:
x_train=pd.get_dummies(x_train,columns=['Deck','Embarked','Sex'],drop_first=True)
x_test=pd.get_dummies(x_test,columns=['Deck','Embarked','Sex'],drop_first=True)
x_train, x_test = x_train.align(x_test,join='left',axis=1,fill_value=0)

In [96]:
#StandardScaler is applied because KNN is a distance-based algorithm. Features with larger scales can dominate the distance calculation.
scale=StandardScaler()
num_col = x_train.select_dtypes(["int64",'float']).columns
x_train[num_col]=scale.fit_transform(x_train[num_col])
x_test[num_col]=scale.transform(x_test[num_col])

In [97]:
knn=KNeighborsClassifier(n_neighbors=4,weights="uniform")

In [98]:
knn.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=4)

In [99]:
pred_y = knn.predict(x_train)

In [100]:
accuracy_score(y_train,pred_y)

0.9452054794520548

In [101]:
accuracy_score(y_train,pred_y)

0.9452054794520548

In [102]:
pred_y_test = knn.predict(x_test)

In [103]:
accuracy_score(y_test,pred_y_test)

0.8809523809523809

In [104]:
gcv_knn=GridSearchCV(estimator=KNeighborsClassifier(),param_grid=\
                     {'n_neighbors':[2,4,5,6],'weights':['uniform','distance']},scoring='accuracy',n_jobs=-1,cv=4)

In [121]:
gcv_knn.fit(x_train,y_train)

GridSearchCV(cv=4, estimator=KNeighborsClassifier(), n_jobs=-1,
             param_grid={'n_neighbors': [2, 4, 5, 6],
                         'weights': ['uniform', 'distance']},
             scoring='accuracy')

In [122]:
gcv_knn.cv_results_

{'mean_fit_time': array([0.01280975, 0.00837618, 0.0052911 , 0.00666422, 0.00651348,
        0.02019697, 0.01915067, 0.00575769]),
 'std_fit_time': array([0.01202823, 0.00467627, 0.00024892, 0.00226991, 0.00101576,
        0.01930401, 0.01037622, 0.00043959]),
 'mean_score_time': array([0.00873739, 0.01493675, 0.01306272, 0.01562726, 0.03472871,
        0.01969975, 0.00912571, 0.00891095]),
 'std_score_time': array([0.00180046, 0.0135247 , 0.01030515, 0.01249688, 0.02426647,
        0.0185089 , 0.00086363, 0.0023298 ]),
 'param_n_neighbors': masked_array(data=[2, 2, 4, 4, 5, 5, 6, 6],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_weights': masked_array(data=['uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'n_neighbors': 2, 'weights': 'uniform'},
  {'n_neighbors': 2, 'weights': 'distance'},
  {'n_neighbors': 4, 'weights': 'uniform'},
  {'n_neighbors': 4, 'weights': 'distance'},
  {'n_neighbors': 5, 'weights': 'uniform'},
  {'n_neighbors': 5, 'weights': 'distance'},
  {'n_neighbors': 6, 'weights': 'uniform'},
  {'n_neighbors': 6, 'weights': 'distance'}],
 'split0_test_score': array([0.95890411, 0.93150685, 0.93150685, 0.97260274, 0.94520548,
        0.95890411, 0.91780822, 0.94520548]),
 'split1_test_score': array([0.95890411, 0.91780822, 0.89041096, 0.95890411, 0.87671233,
        0.91780822, 0.84931507, 0.91780822]),
 'split2_test_score': array([0.8630137 , 0.8630137 , 0.87671233, 0.91780822, 0.93150685,
        0.94520548, 0.93150685, 0.94520548]),
 'split3_test_score': array([0.87671233, 0.89041096, 0.91780822, 0.93150685, 0.90410959,
        0.90410959, 0.87671233, 0.91780822]),
 'mean_test_score': array([0.91438356, 0.90068493, 0.90410959, 0.94520548, 0.91438356,
        0.93150685, 0.89383562, 0.93150685]),
 'std_test_score': array([0.04478321, 0.02630529, 0.02165944, 0.02165944, 0.02630529,
        0.02165944, 0.03266915, 0.01369863]),
 'rank_test_score': array([4, 7, 6, 1, 4, 3, 8, 2], dtype=int32)}

In [111]:
gcv_knn.best_params_

{'n_neighbors': 4, 'weights': 'distance'}

In [112]:
knn_=KNeighborsClassifier(n_neighbors=5,weights="uniform")

In [113]:
gcv_knn.fit(x_train,y_train)

GridSearchCV(cv=4, estimator=KNeighborsClassifier(), n_jobs=-1,
             param_grid={'n_neighbors': [2, 4, 5, 6],
                         'weights': ['uniform', 'distance']},
             scoring='accuracy')

In [114]:
knn_.fit(x_train,y_train)

KNeighborsClassifier()

In [116]:
pred_y_ = knn_.predict(x_train)

In [117]:
accuracy_score(pred_y_,Y_train)

0.9554794520547946

In [118]:
pred_y_test_ = knn_.predict(x_test)

In [119]:
accuracy_score(y_test,pred_y_test_)

0.9285714285714286